### ISSUE TITLE
make build_prod fails in macOS mojave (10.14.3)

### ISSUE THREAD

**Issue by judoal** [oTranscribe/oTranscribe#110]
Downloaded node-v12.16.3.pkg
npm install
 npm install
npm WARN saveError ENOENT: no such file or directory, open '/Volumes/aux/Downloads/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Volumes/aux/Downloads/package.json'
npm WARN Downloads No description
npm WARN Downloads No repository field.
npm WARN Downloads No README data
npm WARN Downloads No license field.

up to date in 0.773s
found 0 vulnerabilities

make build_prod
make build_prod
/Applications/Xcode.app/Contents/Developer/usr/bin/make compile_static
# clear out existing dist folder
rm -rf ./dist
mkdir ./dist
# compile l10n files
for f in src/l10n/*.ini; do (cat "${f}"; echo) >> dist/data.ini; done
# copy over static assets
cp -r src/img src/opensource.htm src/help.htm src/privacy.htm dist/
cp ./node_modules/jakecache/dist/jakecache.js ./node_modules/jakecache/dist/jakecache-sw.js dist/
mkdir dist/help
mv dist/help.htm dist/help/index.html
mkdir dist/privacy
mv dist/privacy.htm dist/privacy/index.html
# manifest
cp -r src/manifest.appcache dist/
echo "# Updated 05/03/2020_11:12:44:N" >> dist/manifest.appcache
# run webpack
./node_modules/webpack/bin/webpack.js -p
(node:61069) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
(Use `node --trace-deprecation ...` to show where the warning was created)
Hash: e4d7e5ea5dec9ed5c97c
Version: webpack 2.7.0
Time: 21444ms
     Asset     Size  Chunks                    Chunk Names
 bundle.js   301 kB       0  [emitted]  [big]  app
   l10n.js  34.7 kB          [emitted]
index.html  11.2 kB          [emitted]
   [0] ./~/jquery/dist/jquery.js 268 kB {0} [built]
   [4] ./src/js/app/player/player.js 7.87 kB {0} [built]
   [8] ./src/js/app/timestamps.js 3.47 kB {0} [built]
   [9] ./src/js/app/ui.js 6.16 kB {0} [built]
  [14] ./src/js/app/texteditor.js 3.26 kB {0} [built]
  [38] ./src/index.js 314 bytes {0} [built]
  [40] ./src/js/app/backup.js 8.41 kB {0} [built]
  [42] ./src/js/app/export.js 4.86 kB {0} [built]
  [43] ./src/js/app/import.js 1.81 kB {0} [built]
  [44] ./src/js/app/init.js 4.8 kB {0} [built]
  [45] ./src/js/app/input.js 14.5 kB {0} [built]
  [46] ./src/js/app/languages.js 2.03 kB {0} [built]
  [47] ./src/js/app/old-browsers.js 823 bytes {0} [built]
  [71] ./src/scss/base.scss 5.72 kB {0} [built] [failed] [1 error]
 [106] multi ./src/index.js 28 bytes {0} [built]
    + 92 hidden modules

ERROR in ./src/scss/base.scss
Module build failed: Error: Cannot find module 'node-sass'
Require stack:
- /Volumes/aux/github/oTranscribe/node_modules/sass-loader/index.js
- /Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/loadLoader.js
- /Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js
- /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModule.js
- /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModuleFactory.js
- /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/Compiler.js
- /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/webpack.js
- /Volumes/aux/github/oTranscribe/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Volumes/aux/github/oTranscribe/node_modules/sass-loader/index.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at loadLoader (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:185:6
    at runSyncOrAsync (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:124:12)
    at /Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:175:3
    at loadLoader (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModule.js:179:3)
    at NormalModule.build (/Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModule.js:268:15)
    at Compilation.buildModule (/Volumes/aux/github/oTranscribe/node_modules/webpack/lib/Compilation.js:146:10)
    at factoryCallback (/Volumes/aux/github/oTranscribe/node_modules/webpack/lib/Compilation.js:329:11)
    at /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModuleFactory.js:253:5
    at /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModuleFactory.js:99:14
 @ ./src/index.js 9:0-27
 @ multi ./src/index.js

ERROR in ./src/scss/base.scss
Module build failed: ModuleBuildError: Module build failed: Error: Cannot find module 'node-sass'
Require stack:
- /Volumes/aux/github/oTranscribe/node_modules/sass-loader/index.js
- /Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/loadLoader.js
- /Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js
- /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModule.js
- /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModuleFactory.js
- /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/Compiler.js
- /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/webpack.js
- /Volumes/aux/github/oTranscribe/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Volumes/aux/github/oTranscribe/node_modules/sass-loader/index.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at loadLoader (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModule.js:179:3)
    at NormalModule.build (/Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModule.js:268:15)
    at Compilation.buildModule (/Volumes/aux/github/oTranscribe/node_modules/webpack/lib/Compilation.js:146:10)
    at /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/Compilation.js:433:9
    at /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModuleFactory.js:253:5
    at /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModuleFactory.js:99:14
    at /Volumes/aux/github/oTranscribe/node_modules/tapable/lib/Tapable.js:268:11
    at NormalModuleFactory.<anonymous> (/Volumes/aux/github/oTranscribe/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Volumes/aux/github/oTranscribe/node_modules/tapable/lib/Tapable.js:272:13)
    at /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModuleFactory.js:74:11
    at /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModuleFactory.js:205:8
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
    at /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModule.js:192:19
    at /Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:170:18
    at loadLoader (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/loadLoader.js:27:11)
    at iteratePitchingLoaders (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModule.js:179:3)
    at NormalModule.build (/Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModule.js:268:15)
    at Compilation.buildModule (/Volumes/aux/github/oTranscribe/node_modules/webpack/lib/Compilation.js:146:10)
    at /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/Compilation.js:433:9
    at /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModuleFactory.js:253:5
    at /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModuleFactory.js:99:14
    at /Volumes/aux/github/oTranscribe/node_modules/tapable/lib/Tapable.js:268:11
    at NormalModuleFactory.<anonymous> (/Volumes/aux/github/oTranscribe/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Volumes/aux/github/oTranscribe/node_modules/tapable/lib/Tapable.js:272:13)
    at /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModuleFactory.js:74:11
    at /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModuleFactory.js:205:8
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
Child html-webpack-plugin for "index.html":
       [0] ./~/raw-loader!./src/html/about.htm 3.42 kB {0} [built]
       [1] ./~/raw-loader!./src/html/google-analytics.htm 509 bytes {0} [built]
       [2] ./~/raw-loader!./src/html/meta-tags.htm 1.25 kB {0} [built]
       [3] ./~/raw-loader!./src/html/settings.htm 55 bytes {0} [built]
       [4] ./~/raw-loader!./src/html/textbox.htm 3.98 kB {0} [built]
       [5] ./~/raw-loader!./src/html/topbar.htm 2.14 kB {0} [built]
       [6] ./~/html-loader?interpolate&attrs=img:data-src!./src/index.htm 888 bytes {0} [built]
Child extract-text-webpack-plugin:
       [0] ./~/css-loader!./~/sass-loader!./src/scss/base.scss 3.44 kB {0} [built] [failed] [1 error]

    ERROR in ./~/css-loader!./~/sass-loader!./src/scss/base.scss
    Module build failed: Error: Cannot find module 'node-sass'
    Require stack:
    - /Volumes/aux/github/oTranscribe/node_modules/sass-loader/index.js
    - /Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/loadLoader.js
    - /Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js
    - /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModule.js
    - /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModuleFactory.js
    - /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/Compiler.js
    - /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/webpack.js
    - /Volumes/aux/github/oTranscribe/node_modules/webpack/bin/webpack.js
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
        at Function.Module._load (internal/modules/cjs/loader.js:890:27)
        at Module.require (internal/modules/cjs/loader.js:1080:19)
        at require (internal/modules/cjs/helpers.js:72:18)
        at Object.<anonymous> (/Volumes/aux/github/oTranscribe/node_modules/sass-loader/index.js:4:12)
        at Module._compile (internal/modules/cjs/loader.js:1176:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
        at Module.load (internal/modules/cjs/loader.js:1040:32)
        at Function.Module._load (internal/modules/cjs/loader.js:929:14)
        at Module.require (internal/modules/cjs/loader.js:1080:19)
        at require (internal/modules/cjs/helpers.js:72:18)
        at loadLoader (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/loadLoader.js:13:17)
        at iteratePitchingLoaders (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:173:18
        at loadLoader (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/loadLoader.js:36:3)
        at iteratePitchingLoaders (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at runLoaders (/Volumes/aux/github/oTranscribe/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
        at NormalModule.doBuild (/Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModule.js:179:3)
        at NormalModule.build (/Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModule.js:268:15)
        at Compilation.buildModule (/Volumes/aux/github/oTranscribe/node_modules/webpack/lib/Compilation.js:146:10)
        at /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/Compilation.js:433:9
        at /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModuleFactory.js:253:5
        at /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModuleFactory.js:99:14
        at /Volumes/aux/github/oTranscribe/node_modules/tapable/lib/Tapable.js:268:11
        at NormalModuleFactory.<anonymous> (/Volumes/aux/github/oTranscribe/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
        at NormalModuleFactory.applyPluginsAsyncWaterfall (/Volumes/aux/github/oTranscribe/node_modules/tapable/lib/Tapable.js:272:13)
        at /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModuleFactory.js:74:11
        at /Volumes/aux/github/oTranscribe/node_modules/webpack/lib/NormalModuleFactory.js:205:8
        at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Comment by amandabee** [comment]
I'm closing out older issues that we don't have the capacity to troubleshoot, including this one.
